apiVersion: v1
kind: Service
metadata:
  name: coverletter-app-service
spec:
  selector:
    app: coverletter-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer